[build]
command = "curl https://mise.run | sh && ~/.local/bin/mise install && ~/.local/bin/mise run build"
publish = "dist/client"

[build.environment]
NODE_VERSION = "24.12.0"
PNPM_VERSION = "10.26.0"
